### PR TITLE
Remove crafting recipes regarding removed jungle sticks

### PR DESCRIPTION
**Pull request by Thomas--S**
Forgotten in 34c01e66c78031ec367fd463f947f790affea4f4

### CODE REVIEW

**Comment by sofar** [comment]
This looks :+1: to me.

**Comment by Thomas--S** [comment]
@sofar Could you please merge this?

**Comment by sofar** [comment]
thanks for the reminder!

**Comment by Thomas--S** [comment]
Thanks for merging!

**Pull request merged**
