### PR TITLE
Craft Circle Stone Brick and Stone tile

### PR DESCRIPTION
**Pull request by Jat15**
Craft Circle Stone Brick was similar furnace.
Stone Tile is more similar with stone block.

### CODE REVIEW

**Comment by Jat15** [comment]
Rebase 1.1.0

**Comment by sofar** [comment]
Needs a rebase, sorry.

**Comment by Jat15** [comment]
Rebase 30/12/2017

**Comment by Jat15** [comment]
Rebase  and Delete >>>>Head 
1/01/2018

**Comment by sofar** [comment]
@fozolo please review!

**Comment by fozolo** [comment]
Good job updating the change log. That  is something I ought to start doing as well. I do not see any problems with these changes but I do have some suggestions as follows.

Regarding the new circle_stone_bricks recipe, I would prefer if the recipe uses a circle of stone instead of the U-shape used here.  I do appreciate the effort to keep the number of input and output blocks equal. If one more stone is added the output would then become 17 blocks which is quite a lot.  Perhaps the coal block could be changed to a coal lump and the recipe output 9 blocks.

Regarding the stone_tile recipe, I agree that using stone as input seems like a better fit than cobble because the texture of stone is a better match for the resulting stone tile texture.  However, stone tile is one of the cheapest 'nice' looking blocks in game and is a very popular choice for large builds by users without creative. Even by doubling the recipe output to 8 blocks, the new recipe is likely increasing the cost of crafting stone tile.

**Comment by Jat15** [comment]
@fozolo 

x  x  x
x  0 x
x  x  x
x= Stone 0 = Coal
For 8 moreblocks:coal_stone or 9

x x x
x x x
x x x
x = moreblocks:coal_stone
For 9 moreblocks:circle_stone_bricks or 9

**Comment by fozolo** [comment]
I seem to have misread the circle_stone_bricks recipe; so please disregard the U-shaped comment.

To be completely clear, I'm suggesting the following recipe for circle stone bricks:
```
minetest.register_craft({
	output = "moreblocks:circle_stone_bricks 9",
	recipe = {
		{"default:stone", "default:stone", "default:stone"},
		{"default:stone", "default:coal_lump", "default:stone"},
		{"default:stone", "default:stone", "default:stone"},
	}
})
```
This seems cheaper to me than
```
minetest.register_craft({
	output = "moreblocks:circle_stone_bricks 16",
	recipe = {
		{"default:stone", "default:stone", "default:stone"},
		{"default:stone", "default:coalblock", "default:stone"},
		{"default:stone", "default:stone", "default:stone"},
	}
})
```
and much cheaper than
```
minetest.register_craft({
	output = "moreblocks:circle_stone_bricks 9",
	recipe = {
		{"default:coal_stone", "default:coal_stone", "default:coal_stone"},
		{"default:coal_stone", "default:coal_stone", "default:coal_stone"},
		{"default:coal_stone", "default:coal_stone", "default:coal_stone"},
	}
})
```
because cobble (used to make stone) is more abundant than coal_lump (used to make coalblock or coal_stone).

What do you think?

**Comment by Jat15** [comment]
If remake coal_stone for simplify use and price : (also apply ironstone)
```
minetest.register_craft({
	output = "moreblocks:coal_stone 9",
	recipe = {
		{"default:stone", "default:stone", "default:stone"},
		{"default:stone", "default:coal_lump", "default:stone"},
		{"default:stone", "default:stone", "default:stone"},
	}
})
```
It will be simpler use this recipe:

```
minetest.register_craft({
	output = "moreblocks:circle_stone_bricks 9",
	recipe = {
		{"default:coal_stone", "default:coal_stone", "default:coal_stone"},
		{"default:coal_stone", "default:coal_stone", "default:coal_stone"},
		{"default:coal_stone", "default:coal_stone", "default:coal_stone"},
	}
})
```
It would be like doing :

```
minetest.register_craft({
	output = "moreblocks:circle_stone_bricks 9",
	recipe = {
		{"default:stone", "default:stone", "default:stone"},
		{"default:stone", "default:coal_lump", "default:stone"},
		{"default:stone", "default:stone", "default:stone"},
	}
})
```
Or simplify more "circle" stone:

```
minetest.register_craft({
	output = "moreblocks:circle_stone_bricks 9",
	recipe = {
		{"", "default:coal_stone", ""},
		{"default:coal_stone", "", "default:coal_stone"},
		{"", "default:coal_stone", ""},
	}
})
```

**Comment by fozolo** [comment]
If the `coal_stone` and `iron_stone` recipes are updated, then their reverse recipes to get `stone` from `coal_stone` and `iron_stone` should be updated as well.

I think the simplest way to resolve the conflict with `default:furnace` is:
```
minetest.register_craft({
	output = "moreblocks:circle_stone_bricks 5",
	recipe = {
		{"", "default:stone", ""}, 
		{"default:stone", "default:coal_lump", "default:stone"},
		{"", "default:stone", ""},
	}
})
```

**Comment by Jat15** [comment]
Wtf reverse craft for coal and iron ....

```
minetest.register_craft({
	output = "default:stone",
	type = "shapeless",
	recipe = {"default:steel_ingot", "moreblocks:coal_stone"},
})
minetest.register_craft({
	output = "default:stone",
	type = "shapeless",
	recipe = {"default:coal_lump", "moreblocks:iron_stone"},
})
```

So expansive and not logical....

```
minetest.register_craft({
	output = "default:stone",
	type = "shapeless",
	recipe = { "moreblocks:coal_stone"},
})
minetest.register_craft({
	output = "default:stone",
	type = "shapeless",
	recipe = { "moreblocks:iron_stone"},
})
```

If I changed iron_stone, coal_stone....

It would easier:

```
minetest.register_craft({
	output = "moreblocks:circle_stone_bricks 8",
	recipe = {
		{"", "moreblocks:coal_stone", ""},
		{"moreblocks:coal_stone", "", "moreblocks:coal_stone"},
		{"", "moreblocks:coal_stone", ""},
	}
})
```
The node will be cheaper...

Resume : 

```
minetest.register_craft({
	output = "moreblocks:coal_stone 9",
	recipe = {
		{"default:stone", "default:stone", "default:stone"},
		{"default:stone", "default:coal_lump", "default:stone"},
		{"default:stone", "default:stone", "default:stone"},
	}
})
minetest.register_craft({
	output = "moreblocks:coal_stone 9",
	recipe = {
		{"default:stone", "default:stone", "default:stone"},
		{"default:stone", "default:steel_ingot", "default:stone"},
		{"default:stone", "default:stone", "default:stone"},
	}
})

minetest.register_craft({
	output = "default:stone",
	type = "shapeless",
	recipe = { "moreblocks:coal_stone"},
})
minetest.register_craft({
	output = "default:stone",
	type = "shapeless",
	recipe = { "moreblocks:iron_stone"},
})

minetest.register_craft({
	output = "moreblocks:circle_stone_bricks 8",
	recipe = {
		{"", "moreblocks:coal_stone", ""},
		{"moreblocks:coal_stone", "", "moreblocks:coal_stone"},
		{"", "moreblocks:coal_stone", ""},
	}
})
```

**Comment by fozolo** [comment]
I agree, the recipes for `coal_stone` and `iron_stone` should be improved, but I think this pull request should focus on fixing the recipe conflict between `circle_stone_bricks` and `default:furnace`.  The other issues should be addressed in a separate pull request.

This recipe:
```
recipe = {
	{"", "moreblocks:coal_stone", ""},
	{"moreblocks:coal_stone", "", "moreblocks:coal_stone"},
	{"", "moreblocks:coal_stone", ""},
}
```
will conflict with `castle:hole_coal_stone` aka Coal Stone Murder Hole.  I don't know if anyone else is using that mod, but I do so I prefer your earlier suggestion.
```
recipe = {
	{"", "default:stone", ""}, 
	{"default:stone", "default:coal_lump", "default:stone"},
	{"", "default:stone", ""},
}
```
Finally I would make the number of output blocks equal to the number of input blocks.  So if the last recipe is used, it should output 5 `circle_stone_bricks`.

**Comment by Jat15** [comment]
For stone tile : 
```

minetest.register_craft({
	output = "moreblocks:stone_tile 9",
	recipe = {
		{"default:cobble", "default:cobble", "default:cobble"},
		{"default:cobble", "default:stone", "default:cobble"},
		{"default:cobble", "default:cobble", "default:cobble"},
	}
})
```

**Comment by fozolo** [comment]
@sofar I think this is ready to merge.

**Pull request merged**
