### PR TITLE
Add a raw_drop field to definition.

### PR DESCRIPTION
**Pull request by Thomas--S**
This allows to use a fixed item to be dropped. (e.g. a seed)

### CODE REVIEW

**Comment by Thomas--S** [comment]
A more detailed explanation why this is needed:
E.g. If you register all stairs/slabs/etc for default:cobble and you want it to always drop e.g. farming:wheat_seed.
The current behaviour is that an shape specific string gets added to the "drop" field.
If you set the new raw_drop option to true, this won't be the case.


If it's still unclear, what I want to do here, please ask.

**Comment by Thomas--S** [comment]
@sofar Can you please merge this?

**Comment by sofar** [comment]
I'm having trouble justifying this change.

- creates a new and complex API that I haven't seen somewhere else
- I find it somewhat confusing
- a node override would solve the issue

For now, I'm negative on this.

**Comment by Thomas--S** [comment]
But then we would need to override over 20 nodes per registration, that's really a lot of unnecessary overhead. If you have a better suggestion, how to allow static drops, I am open to this, but we really need a solution. The static drops are needed for the relaunch of the streets mod.

**Comment by Thomas--S** [comment]
Replaced by #46

**Pull request closed without merging**
