### PR TITLE
Making glass blocks cut by table saw properly visible

### PR DESCRIPTION
**Pull request by h-v-smacker**
With current node definitions, partial glass nodes made on the table saw miss most of their sides. The result is that they are nigh-invisible (save for the decorative "stains" scattered over their supposed surfaces) from most angles. This change reverts the situation, and the glass nodes become properly defined visually.

moreblocks

### CODE REVIEW

**Comment by sofar** [comment]
Looks pretty good to me.

**Comment by fozolo** [comment]
Does this work with connected textures?  Something like this has already been reverted once cc7e1271beac599a4807daaf0999015225e78a2c.

**Comment by h-v-smacker** [comment]
I don't understand the question. The mod in its default state provides subpar visual experience. Are you suggesting that this drawback is to be preserved for compatibility with some other textures?

**Comment by fozolo** [comment]
I meant to say 'connected_glass' not 'connected textures'.  Sorry for the confusion.  I'm referring to the minetest feature that draws connected glass nodes with a single border.  This feature is currently working for the various moreblocks glass types, but will be broken by this pull request (compare the stack of superglow_glass in boxes 1 and 2).  I don't think we should break one visual feature to fix another. Surely there is a way to have both.

connected_texture_comp

**Comment by h-v-smacker** [comment]
ok, so currently the partial blocks made by table saw are sacrificed for the sake of full glass block columns... I see. Indeed, a solution that would fix everything at once would be preferable. Although I would prefer to "break them again" rather than have what it looks like now. At least in my experience, the saw-cut blocks are used a lot more often than full-size blocks.

**Pull request closed without merging**
