### PR TITLE
Improve the placement logic for slabs, etc

### PR DESCRIPTION
**Pull request by Oblomov**
When placing stairs+ nodes with the special / fast key (E), an
alternative placement strategy similar to the one from MTG (and actually
batter, IMO) is used. The new / alternative strategy is as follows:

* items in the same category clone the param2 of the node they're being
  placed next to; this allows putting adjacent slabs/stairs all with the
same orientation without worrying too much;
* otherwise, the orientation for the placement is chosen according to
  the area of the node clicked: this allows placement of “high” slabs by
clicking on the upper half of a side face of another node, and similar
to orient the vertically-placed slabs according to the close/far
position.

### CODE REVIEW

**Comment by Oblomov** [comment]
I'm putting it out here for testing, but it's possible may need some more tuning, especially for the “from the bottom” placement.

**Comment by Oblomov** [comment]
OK this definitely needs more work.

**Comment by Oblomov** [comment]
Revised all the placement computations, now they seem correct. I have tested predominantly with the inner staircase (slap + raised corner): the slab corner corresponding to the raise now always goes to the face quarter that was clicked on. So for me this is now ready for merge, although of course further testing is welcome.

**Comment by Oblomov** [comment]
OK, maybe not yet, I am still having second thoughts about the modifier to use. I want to move to sneak+placement, but this requires some thought about handling of param2 copy.

**Comment by Oblomov** [comment]
New revision of the PR, with further revised, simplified placement rules. These are direct extensions of the standard placement rules, so they do not use a special key. Instead, top/bottom or left/right side of the face, where appropriate, is checked to determine the placement orientation. The aux / special / fast key can still be used to place same-category nodes with the same orientation, or to place nodes as if the placer was on the opposite side otherwise.

**Review by Calinou — APPROVED** [review]
Thanks! I edited the changelog for consistency.

**Comment by BuckarooBanzay** [comment]
@Oblomov maybe i'm using that wrong, but if i now try to place slopes onto a flat surface (without special/E key) the slope gets placed weirdly with the slope part facing the ground :confused:
Building with slopes like this really is a nightmare now, sorry...

Was that your intention or am i using that wrong?

**Comment by OgelGames** [comment]
It's the snow that is causing this. I tested without snow, and they were placed correctly (as in image 1), but when i placed them in snow, they got placed sideways (like image 2).

**Comment by Oblomov** [comment]
Can you please open an issue describing the problem? I'll try to debug this when I can. I've also seen some odd issues on Android, so there's definitely some quirk that needs to be resolved in the new logic.

**Pull request merged**
