### PR TITLE
multi texture models

### PR DESCRIPTION
**Pull request by pithydon**
Minetest allows six textures per node, one for every side.
Old meshes in this mod only allow one texture.

Use cases for this would be for default:tree or default:cactus.
My morerainbows mod would also be affected.

### CODE REVIEW

**Comment by sofar** [comment]
`0 models/moreblocks_slope_outer_cut.obj 100644 → 100755`

You shouldn't change the permission bits to executable. Can you fix?

What actually is changed by the models? I don't see the corresponding texture change.

The `.` inserted into ` models/moreblocks_slope_outer_half.obj ` seems like a bug.

**Comment by pithydon** [comment]
I was wondering what 100644 > 100755 was.
Looks like I have things to fix.
Nothing changed in the default nodes.
I need to add a description.

**Comment by pithydon** [comment]
Added all meshes. Fixed bugs stated above.
I think it's ready to merge now.

**Comment by pithydon** [comment]
Is there any reason this is not getting merged?

**Comment by sofar** [comment]
I need some time to review the new changes, but it's below the 30 day pending threshold (at that time I make prs a priority)

**Comment by sofar** [comment]
2bd998e

**Pull request closed without merging**
