### PR TITLE
Fix name collision between moreblocks and stairsplus code.

### PR DESCRIPTION
**Pull request by ashtrayoz**
moreblocks/stairsplus generates stuff with a set of suffixes, including "_alt", "_alt_1", etc.
But moreblocks already defines a block named moreblocks:stair_split_stone_tile_alt
Crafting with a single moreblocks:stair_split_stone_tile_alt has two conflicting outputs.
One is registered from moreblocks/crafting.lua, one is from stairsplus.

This change renames the base block in moreblocks to "split_stone_tile_other", which resolves the crafting problem.  It will break existing worlds.

There are other ways this could be fixed, but they will probably break existing worlds as well.
More ideas are welcome.

### CODE REVIEW

**Comment by Calinou** [comment]
Maybe add an alias, so that existing worlds aren't broken by this change?

**Comment by sofar** [comment]
Needs a rebase, please?

**Comment by fozolo** [comment]
A picture to clarify the original issue.
screenshot_20171230_102014

This no longer happens because `split_stone_tile_alt` was aliased to `checker_stone_tile`.  However the aliases for the cut versions were missed.

**Comment by sofar** [comment]
#107 replaced this.

**Pull request closed without merging**
